version = 0.1
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::153181783728:user/aws-sam-cli-managed-dev-pipeline-resou-PipelineUser-7pBb0xvyDIae"
permissions_provider = "AWS IAM"

[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::153181783728:role/aws-sam-cli-managed-dev-pipel-PipelineExecutionRole-QeswHYxEvvAs"
cloudformation_execution_role = "arn:aws:iam::153181783728:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionRo-HDJCpeEaOAyf"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-r-artifactsbucket-jv3daiw0rvsp"
image_repository = ""
region = "us-west-2"

[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::153181783728:role/aws-sam-cli-managed-prod-pipe-PipelineExecutionRole-ChWsAZ4YBQsh"
cloudformation_execution_role = "arn:aws:iam::153181783728:role/aws-sam-cli-managed-prod--CloudFormationExecutionRo-Ny4VIjys2VHW"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline--artifactsbucket-otcx4g5ezvcd"
image_repository = ""
region = "us-west-2"
